server:
  port: 8885
  error:
    include-message: always
spring:  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5433/poc_data_jdbc
    username: postgres
    password: postgres
logging:  level:    org.springframework.jdbc.core: TRACE